### PR TITLE
Perf-compare for Hogan.js and Dustjs

### PR DESCRIPTION
**Pull request by druellan**
I've added Hogan.js and Dustjs to the perf-compare test. Dustjs has a "load" method for compiled templates, so I've also added that to the test suite.

### CODE REVIEW

**Comment by BorisMoore** [comment]
Thanks for this. I came across some issues and details - see line comments... I hope to merge and include your request at some point... I have all the above fixes now in my local version...

**Comment by druellan** [comment]
> I think loadSource should be considered part of compiling, so we can remove this test - and include loadSource in the compilation test...

Well, yes, but you can precompile the template. In that case loadSource becomes part of the rendering, but you still can preload the templates at init time to avoid a lag on the render. Thats why I thought that two separate tests where useful. AFAIK

**Comment by BorisMoore** [comment]
Hi Dario. 

I have included Hogan and Dust in the perf comparison: http://borismoore.github.io/jsrender/test/perf-compare.html. I'll close this pull request for now. Let me know if you want to propose pulling something different from what is currently on JsRender test site. Thanks.

Boris

**Comment by druellan** [comment]
Thanks Boris!

No, this is perfect. I'm already running it on a OperaTV emulator (presto) on some restricted hardware (1core 32bits Atom) to peek some numbers.
Thanks again.

**Pull request closed without merging**
