### PR TITLE
Adding cdnjs for jsrender as an installation way...

### PR DESCRIPTION
**Pull request by abdulhannanali**
Requested cdnjs to add a cdn for jsrender. Approved just yesterday after a few weeks.

### CODE REVIEW

**Comment by abdulhannanali** [comment]
The cdnjs issue is here https://github.com/cdnjs/cdnjs/issues/6350

**Comment by BorisMoore** [comment]
Thanks. In fact just today I committed a new update - v0.9.71 - which supersedes 1.0.0-rc.70. It has just been uploaded to npm too. It should fix the autoupdate issue, since I will no longer use version numbers with -rc*.

Would you be able to update to v0.9.71 on cdnjs? Then I will add the info to the JsRender readme.

Also, would you be able to make JsViews available on cdnjs too? https://github.com/BorisMoore/jsviews

**Comment by abdulhannanali** [comment]
@BorisMoore I can request on the cdnjs issue to update it to v0.9.71. also jsviews can be made available by opening another issue on the cdnjs repo.

**Comment by BorisMoore** [comment]
Excellent! Thank you very much!

**Comment by BorisMoore** [comment]
Added to Readme. Thanks again!

**Pull request merged**
